### ISSUE TITLE
Allow Next Schedule To Be Set Immediately After Start

### ISSUE THREAD

**Issue by firrae** [cGuille/async-polling#6]
Hi there,

I'm currently working on a project where we are polling a data server on an interval and this data server has it's own query service that allows me to do a query like NOW-1m to look back 1 minute. This causes an issue with the poller as sometimes the server takes a moment to feed back the info requested leading to the poller scheduling the next loop on an off timeline to what the query is looking at leading to missed data.

The solution to this would be a flag or other way to indicate that the next scheduled poll should be set as soon as the poll happens. This shouldn't affect much as the data fetched is handled asynchronously in my case, and since this feature would be optional it should affect any existing projects.

Thanks,

Steve

**Comment by cGuille** [comment]
Hello Steve,

If I understand well, what you want to achieve is more or less the behavior of `setInterval()`, which is precisely what this library is trying **not** to do.

Also, you should be aware that without [real time computing](https://en.wikipedia.org/wiki/Real-time_computing), it can not be guaranteed that your query will be sent exactly at the right time, and it is impossible to guarantee that it will be received by the server when you want. So if data loss is a serious issue, you should use something else than relative time to query your data source.

If data loss is not that a serious problem, you may want to query your data source with an overlapping time (let's say you query every 50s for the changes of the last 60s) and only handle the items you have not already handled.

In any case, I do not think that the time at which you trigger the poll is very relevant.

Did I misunderstand something?

Guillaume.

**Comment by firrae** [comment]
Hi Guillaume,

Thanks for the response. I believe you mostly understand our issue and your answer indicates that we should likely look at our own implementation, though in the mean time I believe we can get by with this for now after a small modification I made. It's gotten the window down to 8ms from the random 13s we were seeing and causing a bigger issue.

Thanks for the package though, it's certainly a solid one, though not a 100% fit for us. Thanks though!

Steve
